# Generated by Django 4.0.1 on 2022-05-10 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spotId', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('date', models.IntegerField(default=2022, null=True)),
                ('link', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spotId', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=3000)),
                ('found', models.BooleanField(default=False)),
                ('image', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('spotId', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('durationS', models.IntegerField(null=True)),
                ('durationM', models.IntegerField(null=True)),
                ('lyrics', models.TextField(max_length=10000)),
                ('spotLink', models.CharField(max_length=200)),
                ('ytLink', models.CharField(max_length=200)),
                ('album', models.ManyToManyField(blank=True, to='login.Album')),
                ('author', models.ManyToManyField(blank=True, related_name='written_by', to='login.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favs', models.ManyToManyField(blank=True, related_name='likes', to='login.Song')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
