# Generated by Django 4.0.1 on 2022-05-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
