# Generated by Django 4.0.1 on 2022-05-08 23:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_alter_like_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Fav',
        ),
        migrations.AlterModelOptions(
            name='fav',
            options={'ordering': ['created']},
        ),
    ]
