# Generated by Django 4.0.1 on 2022-05-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile_song_delete_fav_profile_favs_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=3000)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='song',
            name='image',
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(default='Paroles indisponibles', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='spot_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='yt_link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='song',
            name='author',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(related_name='in+', to='login.Album'),
        ),
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.ManyToManyField(related_name='by', to='login.Author'),
        ),
    ]
