# Generated by Django 4.0.1 on 2022-05-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_album_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date',
        ),
        migrations.AddField(
            model_name='album',
            name='dat',
            field=models.IntegerField(default=2022, null=True),
        ),
    ]
