# Generated by Django 4.0.1 on 2022-05-09 02:58

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_album_author_remove_song_image_song_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date',
        ),
        migrations.AddField(
            model_name='album',
            name='date',
            field=models.DateField(default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='link',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='desc',
            field=models.TextField(default='', max_length=3000),
            preserve_default=False,
        ),
    ]
