# Generated by Django 4.0.1 on 2022-05-09 03:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_album_desc_remove_author_date_album_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(to='login.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ManyToManyField(to='login.Author'),
        ),
    ]
