# Generated by Django 4.0.1 on 2022-05-09 19:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_album_date_alter_song_album_alter_song_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 9, 19, 20, 41, 12591, tzinfo=utc), null=True),
        ),
    ]
