# Generated by Django 4.0.1 on 2022-05-09 23:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_alter_album_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='spot_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='spot_id',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='feat',
            field=models.ManyToManyField(related_name='feat_by', to='login.Author'),
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 9, 23, 1, 21, 5448, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='author',
            field=models.ManyToManyField(related_name='written_by', to='login.Author'),
        ),
    ]
