# Generated by Django 4.0.1 on 2022-05-09 23:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_album_spot_id_author_spot_id_song_feat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='duration',
            new_name='duration_m',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='feat',
            new_name='feats',
        ),
        migrations.AddField(
            model_name='song',
            name='duration_s',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 9, 23, 32, 21, 186121, tzinfo=utc), null=True),
        ),
    ]
