# Generated by Django 4.0.1 on 2022-05-09 23:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_rename_duration_song_duration_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='found',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 9, 23, 46, 43, 150422, tzinfo=utc), null=True),
        ),
    ]
