# Generated by Django 4.0.1 on 2022-05-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_fav_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fav',
            options={'ordering': ['-date']},
        ),
    ]
