# Generated by Django 4.0.1 on 2022-05-10 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_alter_album_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='spot_id',
            new_name='spotId',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='spot_id',
            new_name='spotId',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='duration_m',
            new_name='durationM',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='duration_s',
            new_name='durationS',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='spot_id',
            new_name='spotId',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='spot_link',
            new_name='spotLink',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='yt_link',
            new_name='ytLink',
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 10, 1, 13, 17, 796778, tzinfo=utc), null=True),
        ),
    ]
