# Generated by Django 4.0.1 on 2022-05-10 01:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_rename_spot_id_album_spotid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='feats',
        ),
        migrations.AlterField(
            model_name='album',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 10, 1, 26, 1, 904288, tzinfo=utc), null=True),
        ),
    ]
